name: actions workflow

on: [push] # trigger on push

jobs: 
# name of job
  run-github-actions:
    runs-on: ubuntu-latest #self-hosted
    steps: 
    - name: Simple JS Action #step name
      id: greet
      uses: actions/hello-world-javascript-action@v1 #like run, uses will take a reference to an action
      # with @ we can specify a branch name, a version or a hash commit
      # the recommanded one is to use version , some commit or branch can be deleted

      #to provide an input, we use with. we can find the input in the doc of action

      with:
        who-to-greet: Rahma

      # to define an output, we should define another step (like ) and we will use run not uses
    - name: Log Greating time
      run: echo "{{$steps.greet.outputs.time}}"
# we want to echo the reference of the action above(actions/hello...), so we need to reference the step before here
# we will make it in run with "{{$steps.greet.outputs.time}}" with a variable which github make it available to us (steps)
# we should define an id to refernece certain steps